"""create raw_events and tenant_write_keys tables

Revision ID: 090478b0046f
Revises: 8d4a2956848d
Create Date: 2026-07-17 01:02:42.351525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '090478b0046f'
down_revision: Union[str, Sequence[str], None] = '8d4a2956848d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_events',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('anonymous_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_tenant_id'), 'raw_events', ['tenant_id'], unique=False)
    op.create_table('tenant_write_keys',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('write_key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_write_keys_tenant_id'), 'tenant_write_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_write_keys_write_key_hash'), 'tenant_write_keys', ['write_key_hash'], unique=True)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tenant_write_keys_write_key_hash'), table_name='tenant_write_keys')
    op.drop_index(op.f('ix_tenant_write_keys_tenant_id'), table_name='tenant_write_keys')
    op.drop_table('tenant_write_keys')
    op.drop_index(op.f('ix_raw_events_tenant_id'), table_name='raw_events')
    op.drop_table('raw_events')
    # ### end Alembic commands ###
