"""add last_four to tenant_write_keys

Revision ID: b5b775b46304
Revises: 090478b0046f
Create Date: 2026-07-17 01:39:10.684696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b775b46304'
down_revision: Union[str, Sequence[str], None] = '090478b0046f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_write_keys', sa.Column('last_four', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_write_keys', 'last_four')
    # ### end Alembic commands ###
