"""create accounts, identity_map, staging_hubspot_companies, staging_hubspot_deals

Revision ID: de4ad7a3110e
Revises: b5b775b46304
Create Date: 2026-07-17 15:36:55.496982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4ad7a3110e'
down_revision: Union[str, Sequence[str], None] = 'b5b775b46304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('hubspot_company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('firm_type', sa.String(), nullable=False),
    sa.Column('contract_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('staging_hubspot_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('hubspot_company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('firm_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_hubspot_companies_hubspot_company_id'), 'staging_hubspot_companies', ['hubspot_company_id'], unique=True)
    op.create_index(op.f('ix_staging_hubspot_companies_tenant_id'), 'staging_hubspot_companies', ['tenant_id'], unique=False)
    op.create_table('identity_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('anonymous_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_map_account_id'), 'identity_map', ['account_id'], unique=False)
    op.create_index(op.f('ix_identity_map_anonymous_id'), 'identity_map', ['anonymous_id'], unique=False)
    op.create_index(op.f('ix_identity_map_tenant_id'), 'identity_map', ['tenant_id'], unique=False)
    op.create_table('staging_hubspot_deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('hubspot_deal_id', sa.String(), nullable=False),
    sa.Column('hubspot_company_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('entered_stage_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hubspot_company_id'], ['staging_hubspot_companies.hubspot_company_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_hubspot_deals_hubspot_company_id'), 'staging_hubspot_deals', ['hubspot_company_id'], unique=False)
    op.create_index(op.f('ix_staging_hubspot_deals_hubspot_deal_id'), 'staging_hubspot_deals', ['hubspot_deal_id'], unique=True)
    op.create_index(op.f('ix_staging_hubspot_deals_tenant_id'), 'staging_hubspot_deals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staging_hubspot_deals_tenant_id'), table_name='staging_hubspot_deals')
    op.drop_index(op.f('ix_staging_hubspot_deals_hubspot_deal_id'), table_name='staging_hubspot_deals')
    op.drop_index(op.f('ix_staging_hubspot_deals_hubspot_company_id'), table_name='staging_hubspot_deals')
    op.drop_table('staging_hubspot_deals')
    op.drop_index(op.f('ix_identity_map_tenant_id'), table_name='identity_map')
    op.drop_index(op.f('ix_identity_map_anonymous_id'), table_name='identity_map')
    op.drop_index(op.f('ix_identity_map_account_id'), table_name='identity_map')
    op.drop_table('identity_map')
    op.drop_index(op.f('ix_staging_hubspot_companies_tenant_id'), table_name='staging_hubspot_companies')
    op.drop_index(op.f('ix_staging_hubspot_companies_hubspot_company_id'), table_name='staging_hubspot_companies')
    op.drop_table('staging_hubspot_companies')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
