FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install --no-root

COPY src ./src
COPY data ./data

ENV PYTHONPATH=/app/src:/app

ENTRYPOINT ["python"]
